// flow-typed signature: 5ca358d01d421b4376e5b37a43da929b
// flow-typed version: <<STUB>>/twitter-lite_v0.14.0/flow_v0.127.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'twitter-lite'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'twitter-lite' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'twitter-lite/dist/stream' {
  declare module.exports: any;
}

declare module 'twitter-lite/dist/stream.m' {
  declare module.exports: any;
}

declare module 'twitter-lite/dist/stream.umd' {
  declare module.exports: any;
}

declare module 'twitter-lite/dist/twitter' {
  declare module.exports: any;
}

declare module 'twitter-lite/dist/twitter.m' {
  declare module.exports: any;
}

declare module 'twitter-lite/dist/twitter.umd' {
  declare module.exports: any;
}

// Filename aliases
declare module 'twitter-lite/dist/stream.js' {
  declare module.exports: $Exports<'twitter-lite/dist/stream'>;
}
declare module 'twitter-lite/dist/stream.m.js' {
  declare module.exports: $Exports<'twitter-lite/dist/stream.m'>;
}
declare module 'twitter-lite/dist/stream.umd.js' {
  declare module.exports: $Exports<'twitter-lite/dist/stream.umd'>;
}
declare module 'twitter-lite/dist/twitter.js' {
  declare module.exports: $Exports<'twitter-lite/dist/twitter'>;
}
declare module 'twitter-lite/dist/twitter.m.js' {
  declare module.exports: $Exports<'twitter-lite/dist/twitter.m'>;
}
declare module 'twitter-lite/dist/twitter.umd.js' {
  declare module.exports: $Exports<'twitter-lite/dist/twitter.umd'>;
}
